# Generated by Django 4.1.7 on 2023-04-22 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_emailform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailForm',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='room',
        ),
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.EmailField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='username',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
