# Generated by Django 4.1.7 on 2023-04-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_signup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='room',
        ),
        migrations.AddField(
            model_name='userlogin',
            name='email',
            field=models.EmailField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
