# Generated by Django 4.1.7 on 2023-04-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_userlogin_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='email',
        ),
    ]
