# Generated by Django 4.1.7 on 2023-04-22 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_userlogin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.room'),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='email',
            field=models.EmailField(default='', max_length=200, unique=True),
        ),
    ]
