# Generated by Django 4.2 on 2023-04-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_userlogin_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
